import { describe, expect, it, vi, beforeEach } from "vitest";

/** The editor works on the workflow's own yaml.
 *
 * That is the point: a workflow written by hand, generated by a recipe, or
 * built in the graph editor are the same artifact, and what you save is what
 * the supervisor runs. So the route is a thin, honest pipe to `workflow
 * cat`/`save` — including the refusals.
 */

const runJigga = vi.fn();
const runJiggaWithInput = vi.fn();

vi.mock("@/lib/jigga-cli", () => ({
  runJigga: (args: string[]) => runJigga(args),
  runJiggaJson: vi.fn(),
  runJiggaWithInput: (args: string[], input: string) => runJiggaWithInput(args, input),
}));

const { GET, PUT } = await import("./route");

const params = (workflowId: string) => ({ params: Promise.resolve({ workflowId }) });
const YAML = "id: release_flow\nname: Release\n";

beforeEach(() => {
  runJigga.mockReset();
  runJiggaWithInput.mockReset();
  runJigga.mockResolvedValue({ ok: true, exitCode: 0, stdout: YAML, stderr: "" });
  runJiggaWithInput.mockResolvedValue({ ok: true, exitCode: 0, stdout: "{}", stderr: "" });
});

describe("GET", () => {
  it("returns the raw yaml", async () => {
    const res = await GET(new Request("http://localhost/x"), params("release_flow"));
    expect(runJigga).toHaveBeenCalledWith(["workflow", "cat", "release_flow"]);
    await expect(res.json()).resolves.toMatchObject({ id: "release_flow", content: YAML });
  });

  it("404s an unknown workflow with core's words", async () => {
    runJigga.mockResolvedValue({ ok: false, exitCode: 1, stdout: "Workflow not found: 'nope'.", stderr: "" });
    const res = await GET(new Request("http://localhost/x"), params("nope"));
    expect(res.status).toBe(404);
    await expect(res.json()).resolves.toMatchObject({ error: expect.stringContaining("not found") });
  });

  it("refuses a flag-shaped id before shelling out", async () => {
    const res = await GET(new Request("http://localhost/x"), params("--home"));
    expect(res.status).toBe(400);
    expect(runJigga).not.toHaveBeenCalled();
  });
});

describe("PUT", () => {
  it("saves through core so the same validator applies, with the yaml on stdin", async () => {
    // On stdin rather than argv: argv is world-readable through /proc, and a
    // workflow definition can name secrets, hosts and paths.
    runJiggaWithInput.mockResolvedValue({ ok: true, exitCode: 0, stdout: '{"workflow":"release_flow"}', stderr: "" });
    const res = await PUT(new Request("http://localhost/x", {
      method: "PUT", body: JSON.stringify({ content: YAML }),
    }), params("release_flow"));
    const [args, input] = runJiggaWithInput.mock.calls[0];
    expect(args).toEqual(["workflow", "save", "release_flow", "--json"]);
    expect(input).toBe(YAML);
    expect(args.join(" ")).not.toContain("release_flow\nname");
    expect(res.status).toBe(200);
  });

  it("surfaces a refused cycle rather than a generic failure", async () => {
    // A graph editor can draw what a runtime cannot run; the reason is the
    // useful part, and it must come from the validator the supervisor uses.
    runJiggaWithInput.mockResolvedValue({
      ok: false, exitCode: 1,
      stdout: "! Not saved — workflow release_flow: workflow graph has a cycle", stderr: "",
    });
    const res = await PUT(new Request("http://localhost/x", {
      method: "PUT", body: JSON.stringify({ content: YAML }),
    }), params("release_flow"));
    expect(res.status).toBe(400);
    await expect(res.json()).resolves.toMatchObject({ error: expect.stringContaining("cycle") });
  });

  it("refuses a flag-shaped id before writing anything", async () => {
    const res = await PUT(new Request("http://localhost/x", {
      method: "PUT", body: JSON.stringify({ content: YAML }),
    }), params("--home"));
    expect(res.status).toBe(400);
    expect(runJiggaWithInput).not.toHaveBeenCalled();
  });
});
