import { NextResponse } from "next/server";
import { runJigga, runJiggaWithInput } from "@/lib/jigga-cli";

/** One workflow's definition: read it, write it back.
 *
 * The editor works on the yaml itself rather than a private model of it, so a
 * workflow written by hand, generated by a recipe, or applied from a suggestion
 * all edit identically — and what you save is what the supervisor runs.
 */

function badArg(value: string): boolean {
  return !value || value.startsWith("-");
}

export async function GET(_request: Request, context: { params: Promise<{ workflowId: string }> }) {
  const { workflowId } = await context.params;
  if (badArg(workflowId)) return NextResponse.json({ error: "invalid id" }, { status: 400 });
  const res = await runJigga(["workflow", "cat", workflowId]);
  if (!res.ok) {
    return NextResponse.json(
      { error: res.stdout.trim() || res.stderr.trim() || "not found" },
      { status: 404 },
    );
  }
  return NextResponse.json({ id: workflowId, content: res.stdout });
}

/** PUT {content} → `workflow save`, which validates before writing.
 *
 * A graph editor can express things a runtime cannot run — an edge to a node
 * you just deleted, a cycle drawn by accident — so the refusal has to come from
 * the same validator the supervisor trusts, not from a second opinion here.
 */
export async function PUT(request: Request, context: { params: Promise<{ workflowId: string }> }) {
  const { workflowId } = await context.params;
  if (badArg(workflowId)) return NextResponse.json({ error: "invalid id" }, { status: 400 });
  const body = (await request.json().catch(() => ({}))) as { content?: string };
  const res = await runJiggaWithInput(["workflow", "save", workflowId, "--json"],
                                      String(body.content ?? ""));
  if (!res.ok) {
    return NextResponse.json(
      { error: res.stdout.trim() || res.stderr.trim() || "save failed" },
      { status: 400 },
    );
  }
  try {
    return NextResponse.json(JSON.parse(res.stdout));
  } catch {
    return NextResponse.json({ ok: true });
  }
}
